services :
  postgres:
    container_name: postgres-sql-bsn
    image: postgres
    environment:
      POSTGRES_USER : nom
      POSTGRES_PASSWORD : password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: espace_client
    volumes:
      -  postgres:/data/postgres
    ports:
      - 5432:5432

    networks:
      - spring-demo
    restart: unless-stopped

networks:
  spring-demo:
    driver: bridge
volumes:
   postgres:
    driver: local



